model:
  target: models.models2.DBTFuse1
  params:
      num_features: 48
      out_channels: 1
      in_channels: 1
      patch_size: 16
  pretrained: 
train:
  accumulation_steps: 8
  epochs: 100
  optimizer:
    target: torch.optim.Adam
    params:
      lr: 1.e-4

dataset:
  ratio: [0.8, 0.2]
  batch_size: 16
  shuffle: true
  url:
    LLVIP: /root/autodl-tmp/data/traindata/LLVIP

